---
baseURL: https://staging.recspert.com
languageCode: en-us
title: Recspert
theme: piko
paginate: "9"
copyright:
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false
ignoreErrors:
  - error-remote-getjson

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    yandex:
      SiteVerificationTag: # Yandex Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: production
  author: Recspert
  description: Recspert - virtual recreation center
  math: false
  images:
  - "/uploads/og.webp"
  label:
    icon: /images/new-logo.svg
    iconHeight: "140"
    iconWidth: "50"
  comments: true
  mainSections:
  - blog
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: # Get link from https://formsubmit.io or https://fabform.io
  assets:
    disableFingerprinting: false
    favicon: /images/new-logo.svg
    favicon16x16: /images/new-logo.svg
    favicon32x32: /images/new-logo.svg
    apple_touch_icon: /images/new-logo.svg
    safari_pinned_tab: /images/new-logo.svg
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    # Hero Section
    showHeroSection: true
    heroUpperTitle: 
    heroTitle: Recspert
    heroDescription: Your ultimate virtual recreation center
    heroCTAPrimaryText: Blog
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Contact
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundVideo: "https://www.recspert.com/video/respect_new_vid.mp4"
    # Blog Section
    showBlogSection: true
    blogTitle: Latest Posts
    blogDescription: This is my latest blog posts
    seeMoreText: More Posts
    showTeamSection: true
    teamTitle: Meet the team
    team:
      - name: Katie
        role: CEO
        imageUrl: /images/team/katie.png
      - name: Tess
        role: Marketing Manager
        imageUrl: /images/team/tess.png
      - name: Liz
        role: Digital Strategy Manager
        imageUrl: /images/team/liz.png
      - name: Alberto
        role: Software Engineer
        imageUrl: /images/team/alberto.png
    # About Section    
    showAboutSection: true
    aboutTitle: How it works
    aboutDescription:
    aboutImgUrl: "/uploads/self.webp"
    aboutVideoUrl: "https://recspert.com/video/tutorial.mp4"
    aboutContent: Hi guys. This is where you put something about yourself.
    # Portfolio Section
    showPortfolioSection: false
    portfolioTitle: Portfolio
    portfolioDescription: Some of my works
    portfolio:
    - imageUrl: /uploads/0b2966e8342db31a9d907bcf1bf93376.jpg
      alt: # image alt for better SEO
      description: Portfolio One.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-2.webp
      alt: # image alt for better SEO
      description: Portfolio Two.
      websiteUrl: #
    - imageUrl: /uploads/portfolio-3.webp
      alt: # image alt for better SEO
      description: Portfolio Three.
      websiteUrl: #
  # Search Options (https://fusejs.io/)
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    js:
    - link: plugins/js/feather.min.js
menus:
  main: # Main Menu
  - name: Meet the Team
    title: TEAM
    url: "/#team"
    weight: "20"
  - name: How it Works
    title: HOW IT WORKS
    pre:
    url: "/#about"
    weight: "30"
  - name: Our Blog
    title: BLOG
    url: "/blog"
    weight: "40"
  - name: Join us
    title: JOIN US
    url: http://app.staging.recspert.com/
    weight: "50"
