---
baseURL: https://imaginative-blancmange-0128e6.netlify.app
languageCode: en-us
title: Recspert
theme: piko
paginate: "9"
copyright: 2023 Recspert
googleAnalytics: 
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false
params:
  analytics:
    google:
      SiteVerificationTag: 
    yandex:
      SiteVerificationTag: 
    bing:
      SiteVerificationTag: 
  env: production
  author: Your Name
  description: Your website description
  math: false
  images:
  - "/uploads/og.webp"
  label:
    icon: "/images/new-logo.svg"
    iconHeight: "140"
    iconWidth: "50"
  comments: true
  mainSections:
  - blog
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: "/legal/privacy/#cookies-and-web-beacons"
  CookieButton: Cookies Policy
  disableAnchoredHeadings: false
  contactFormAction: 
  assets:
    disableFingerprinting: false
    favicon: "/images/new-logo.svg"
    favicon16x16: "/images/new-logo.svg"
    favicon32x32: "/images/new-logo.svg"
    apple_touch_icon: "/images/new-logo.svg"
    safari_pinned_tab: "/images/new-logo.svg"
  ShowReadingTime: true
  ShowBreadCrumbs: true
  homepage:
    disableHeroSection: false
    heroUpperTitle: 
    heroTitle: Recspert
    heroDescription: Your ultimate virtual recreation center
    heroCTAPrimaryText: Blog
    heroCTAPrimaryUrl: "/blog/"
    heroCTASecondaryText: Contact
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "/uploads/portfolio-1.webp"
    disableBlogSection: false
    blogTitle: Latest Posts
    blogDescription: This is my latest blog posts
    seeMoreText: More Posts
    disableAboutSection: false
    aboutTitle: About
    aboutDescription: Just something about me
    aboutImgUrl: "/uploads/self.webp"
    aboutContent: Hi guys. This is where you put something about yourself.
    disablePortfolioSection: false
    portfolioTitle: Portfolio
    portfolioDescription: Some of my works
    portfolio:
    - imageUrl: "/uploads/portfolio-1.webp"
      alt: 
      description: Portfolio One.
      websiteUrl: 
    - imageUrl: "/uploads/portfolio-2.webp"
      alt: 
      description: Portfolio Two.
      websiteUrl: 
    - imageUrl: "/uploads/portfolio-3.webp"
      alt: 
      description: Portfolio Three.
      websiteUrl: 
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: "0"
    distance: "1000"
    threshold: "0.4"
    minMatchCharLength: "0"
    keys:
    - title
    - permalink
    - summary
    - content
  plugins:
    js:
    - link: plugins/js/feather.min.js
menus:
  main:
  - name: Blog
    title: Blog
    pre: pen-tool
    url: "/blog"
    weight: "20"
  - name: Search
    title: Search
    pre: search
    url: "/search"
    weight: "30"
  - name: Contact
    title: Contact
    pre: mail
    url: "/contact"
    weight: "40"
  - name: Get Started
    title: Get Started
    pre: 
    url: "/login"
    weight: "50"
  search:
  - name: Categories
    title: Categories
    url: "/categories"
    weight: "10"
  - name: Archives
    title: Archives
    url: "/archives"
    weight: "20"
  - name: Tags
    title: Tags
    url: "/tags"
    weight: "30"
